name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Java JDK
      run: sudo apt-get install -y openjdk-11-jdk

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget tar unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        mkdir -p $HOME/Android/Sdk/cmdline-tools
        unzip commandlinetools-linux-7583922_latest.zip -d $HOME/Android/Sdk/cmdline-tools
        mv $HOME/Android/Sdk/cmdline-tools/cmdline-tools $HOME/Android/Sdk/cmdline-tools/latest
        yes | $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        $HOME/Android/Sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

    - name: Set up Android environment variables
      run: |
        echo "ANDROID_HOME=$HOME/Android/Sdk" >> $GITHUB_ENV
        echo "PATH=$PATH:$ANDROID_HOME/emulator" >> $GITHUB_ENV
        echo "PATH=$PATH:$ANDROID_HOME/tools" >> $GITHUB_ENV
        echo "PATH=$PATH:$ANDROID_HOME/tools/bin" >> $GITHUB_ENV
        echo "PATH=$PATH:$ANDROID_HOME/platform-tools" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: |
        cd android
        ./gradlew assembleRelease
